<a href="https://colab.research.google.com/github/DubblePos/Colab/blob/main/Ch01.%ED%8C%8C%EC%9D%B4%EC%8D%AC%20%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D%20%EA%B8%B0%EC%B4%88/2_Numpy_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
날짜 : 2021/10/18
이름 : 박승필
내용 : 파이썬 Numpy 패키지 실습하기

Numpy 라이브러리
 - 고성능의 수치계산을 위한 파이썬 라이브러리
 - 파이썬의 기본 리스트보다 월등한 연산 성능
 - 행렬이나 대규모 다차원 배열 처리를 지원
"""
import numpy as np

In [ ]:
# numpy 벡터
v1 = np.array([1, 2, 3, 4, 5])
print('v1 :', v1)

v2 = np.arange(5)
print('v2 :', v2)

v3=np.arange(10)
print('v3 :', v3)

v1 : [1 2 3 4 5]
v2 : [0 1 2 3 4]
v3 : [0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 0 ~ 1 사이의 임의의 실수 100개
result1 = np.random.rand(100)

# 표준정규분포를 따르는 실수 100개
result2 = np.random.randn(100)

# 0 -9 사이의 임의의 정수
result3 = np.random.randint(10)

In [ ]:
result1, result2, result3

(array([0.27412732, 0.85827452, 0.64151658, 0.13426071, 0.97615878,
        0.82477876, 0.4959898 , 0.8587513 , 0.44103765, 0.69861065,
        0.74987894, 0.24367376, 0.39059513, 0.43981442, 0.37144038,
        0.90027172, 0.82196354, 0.73600865, 0.40113047, 0.41822861,
        0.94586165, 0.3829446 , 0.39433095, 0.20279876, 0.01079363,
        0.11945757, 0.81308484, 0.61725048, 0.58412093, 0.10783035,
        0.208149  , 0.3494153 , 0.20410785, 0.54923227, 0.6617146 ,
        0.20363265, 0.29090749, 0.80211677, 0.40798511, 0.4303208 ,
        0.27051284, 0.69402824, 0.76359792, 0.66736439, 0.50751107,
        0.12787878, 0.98378485, 0.99562367, 0.8719447 , 0.02203239,
        0.1232605 , 0.23269979, 0.52299834, 0.83514959, 0.50592221,
        0.3261574 , 0.95599934, 0.39980152, 0.49148745, 0.40767445,
        0.13870513, 0.44799019, 0.54210804, 0.69746799, 0.15636592,
        0.72985072, 0.34524634, 0.55853515, 0.50858424, 0.65138466,
        0.58145329, 0.45996316, 0.1864906 , 0.42

In [ ]:
# numpy 행렬
m1 = np.array([[1, 2], [3, 4]])
print(m1)

m2 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(m2)

m3 = np.ones([2, 4])
print(m3)

m4 = np.zeros([3, 2])
print(m4)

[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# 행렬 인덱싱
mat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(mat)

print(mat[0, 0])
print(mat[0, :])
print(mat[:, 0])

print(mat[0:2, 0:2])
print(mat[:, 0:2])
print(mat[:, 2:4])
print(mat[1:3, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[1 2 3 4]
[1 5 9]
[[1 2]
 [5 6]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]
[[ 6  7]
 [10 11]]
